param([string]$BaseUrl="https://lab-multiplayer.onrender.com",[ValidateSet("baseline","lab")][string]$Mode="baseline",[ValidateSet(10,50)][int]$Burst=10,[int]$Runs=3)
$ErrorActionPreference="Stop"
function LabTest-ConnectBurst($Credentials){$s=[Net.WebSockets.ClientWebSocket]::new();$u=$BaseUrl.Replace("https://","wss://").Replace("http://","ws://")+"/v1/ws";$s.ConnectAsync([Uri]$u,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;$h=@{type="resume";protocol=1;roomId=$Credentials.roomId;playerId=$Credentials.playerId;resumeToken=$Credentials.resumeToken;afterSeq=0;mode=$Mode}|ConvertTo-Json -Compress;$b=[Text.Encoding]::UTF8.GetBytes($h);$s.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;return $s}
function LabTest-ReadBurst($s,[int]$TimeoutSeconds=12){$c=[Threading.CancellationTokenSource]::new([TimeSpan]::FromSeconds($TimeoutSeconds));try{$b=New-Object byte[] 65536;$p=[Text.StringBuilder]::new();do{$r=$s.ReceiveAsync([ArraySegment[byte]]::new($b),$c.Token).GetAwaiter().GetResult();[void]$p.Append([Text.Encoding]::UTF8.GetString($b,0,$r.Count))}while(-not $r.EndOfMessage);return $p.ToString()|ConvertFrom-Json}finally{$c.Dispose()}}
function LabTest-SendBurst($s,[string]$id,[uint64]$seq,[int]$actor,[string]$prefix){$m=@{type="trusted_command";action=@{commandId=$id;seq=$seq;expectedSeq=$seq;actorIndex=$actor;kind="trusted_command";command=@{type="priority_action";action_ref=@{kind="burst_concurrency_test"}};prefixHash=$prefix}}|ConvertTo-Json -Depth 10 -Compress;$b=[Text.Encoding]::UTF8.GetBytes($m);return $s.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None)}
function LabTest-CloseBurst($s){try{$s.CloseAsync([Net.WebSockets.WebSocketCloseStatus]::NormalClosure,"burst",[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null}catch{$s.Abort()};$s.Dispose()}
function LabTest-DiagnosticBurst($Credentials){Invoke-RestMethod "$BaseUrl/v1/rooms/$($Credentials.roomId)/diagnostics" -Method Post -ContentType "application/json" -Body (ConvertTo-Json @{playerId=$Credentials.playerId;resumeToken=$Credentials.resumeToken})}
function LabTest-RunBurst([int]$Run){$room=Invoke-RestMethod "$BaseUrl/v1/rooms" -Method Post -ContentType "application/json" -Body '{"name":"A"}';$guest=Invoke-RestMethod "$BaseUrl/v1/rooms/$($room.roomId)/players" -Method Post -ContentType "application/json" -Body '{"name":"B"}';$a=LabTest-ConnectBurst $room;$b=LabTest-ConnectBurst $guest;$null=LabTest-ReadBurst $a;$null=LabTest-ReadBurst $b;$before=LabTest-DiagnosticBurst $room;$tasks=[Collections.Generic.List[Threading.Tasks.Task]]::new();for($i=0;$i -lt $Burst;$i++){[void]$tasks.Add((LabTest-SendBurst $a "burst-a-$Run-$i" 0 $room.playerIndex ""));[void]$tasks.Add((LabTest-SendBurst $b "burst-b-$Run-$i" 0 $guest.playerIndex ""))};[void][Threading.Tasks.Task]::WhenAll($tasks).GetAwaiter().GetResult();Start-Sleep -Seconds 2;$after=LabTest-DiagnosticBurst $room;$accepted=[int]$after.room.currentSeq-[int]$before.room.currentSeq;$prefix=$after.room.recentEvents[-1].prefixHash;$postAId="burst-post-a-$Run";LabTest-SendBurst $a $postAId $after.room.currentSeq $room.playerIndex $prefix|ForEach-Object{$_.GetAwaiter().GetResult()}|Out-Null;Start-Sleep -Milliseconds 500;$postA=LabTest-DiagnosticBurst $room;$postPrefix=$postA.room.recentEvents[-1].prefixHash;LabTest-SendBurst $b "burst-post-b-$Run" $postA.room.currentSeq $guest.playerIndex $postPrefix|ForEach-Object{$_.GetAwaiter().GetResult()}|Out-Null;Start-Sleep -Milliseconds 500;$final=LabTest-DiagnosticBurst $room;$result=[ordered]@{mode=$Mode;run=$Run;burstPerClient=$Burst;sent=$Burst*2;acceptedDuringBurst=$accepted;conflicts=[int]$after.room.metrics.conflicts-[int]$before.room.metrics.conflicts;duplicates=[int]$final.room.metrics.duplicates-[int]$before.room.metrics.duplicates;finalSeq=$final.room.currentSeq;postBurstA=($postA.room.currentSeq -gt $after.room.currentSeq);postBurstB=($final.room.currentSeq -gt $postA.room.currentSeq);activeConnections=$final.room.activeConnections};LabTest-CloseBurst $a;LabTest-CloseBurst $b;return $result}
1..$Runs|ForEach-Object{LabTest-RunBurst $_}
